import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/kovac/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({channel:'chrome',headless:true});
const origin=process.env.QA_ORIGIN||'http://127.0.0.1:3013';
try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(origin+'/admin');
  await page.locator('#login-form [name=email]').fill('preview@example.test');
  await page.locator('#login-form [name=password]').fill('local-preview-only-2026');
  await page.locator('#login-form button').first().click();
  await page.locator('[data-view=settings]').click();
  await page.locator('[data-edit]').first().click();
  await page.locator('.add-social').click();
  await page.locator('[data-social-url]').first().fill('https://www.instagram.com/citypraxis.test/');
  await page.locator('.add-social').click();
  await page.locator('[data-social-platform]').last().selectOption('facebook');
  await page.locator('[data-social-url]').last().fill('https://www.facebook.com/citypraxis.test/');
  assert.equal(await page.locator('.add-social').isDisabled(),true);
  await page.locator('#content-form button[value=publish]').click();
  await page.locator('#editor-dialog').waitFor({state:'hidden'});
  await page.goto(origin+'/?lang=en');
  await mkdir('test-results',{recursive:true});
  assert.equal(await page.locator('.footer-social a').count(),2);
  assert.equal(await page.locator('.footer-social a').first().getAttribute('href'),'https://www.instagram.com/citypraxis.test/');
  assert.equal(await page.locator('.footer-social a').last().getAttribute('href'),'https://www.facebook.com/citypraxis.test/');
  await page.locator('.cookie-acknowledge').click();
  await page.locator('.footer-top').screenshot({path:'test-results/footer-social.png'});
  const review=page.locator('.reviews-grid .review-card').first();
  await review.scrollIntoViewIfNeeded();
  await review.waitFor({state:'visible'});
  await page.waitForTimeout(850);
  assert.equal(await review.evaluate(el=>el.classList.contains('is-visible')),true);
  await page.locator('.reviews-grid').screenshot({path:'test-results/reviews-reveal.png'});
  assert.deepEqual(errors,[]);
  console.log('social admin editor, footer links and review reveal passed');
}finally{await browser.close();}
