export const seed = {
  settings: [{ id: 'practice', title: 'Praxisinformationen', email: 'info@citypraxis.wien', phone: '+43 699 12682157', address: 'Stubenbastei 12/11', city: '1010 Wien', hours: 'Termine nach Vereinbarung', saturday: 'Samstag 08:30–12:30 Uhr', payment: 'Bitte bezahlen Sie Ihre Behandlung vor Ort in bar.', acute: 'Akuttermin benötigt? Rufen Sie uns an.', acuteAvailable: false }],
  pages: [
    { id: 'home', title: 'Wo andere aufhören,', subtitle: 'fangen wir erst an.', intro: 'Spezialisierte Therapie für Kiefer, Kopf und Bewegungsapparat. Mit Zeit, Erfahrung und einem gemeinsamen Blick auf das, was Sie bewegt.', eyebrow: 'IHRE GESUNDHEIT. UNSER ZUSAMMENSPIEL.', image: '/assets/hero.jpg' },
    { id: 'about', title: 'Viele Perspektiven. Ein gemeinsames Ziel.', intro: 'Wir verbinden Physiotherapie, Osteopathie, Logopädie und Heilmassage. Für eine Behandlung, die den Menschen als Ganzes sieht.', body: 'Komplexe Beschwerden brauchen einen aufmerksamen Blick. In der Citypraxis arbeiten unterschiedliche Fachrichtungen zusammen und stimmen die nächsten Schritte individuell mit Ihnen ab.\n\nUnser Schwerpunkt liegt auf Beschwerden im Kiefer-, Kopf- und Nackenbereich. Ebenso begleiten wir Sie bei orthopädischen Beschwerden und auf Ihrem Weg zurück in den Alltag nach einer Operation oder Verletzung.' },
    { id: 'impressum', title: 'Impressum', intro: 'Die Angaben für diese neue Website werden vor der Veröffentlichung ergänzt.', body: 'Kontakt zur Praxis: info@citypraxis.wien\nStubenbastei 12/11, 1010 Wien\n\nDieser lokale Entwurf enthält noch kein vollständiges Impressum.', status: 'draft' },
    { id: 'datenschutz', title: 'Datenschutz', intro: 'Die Datenschutzhinweise werden vor der Veröffentlichung ergänzt.', body: 'Lokaler Entwicklungsstand: Terminanfragen werden in der lokalen Datenbank gespeichert. Verwenden Sie für die Vorschau ausschließlich Testdaten. Die finale Datenschutzerklärung, Aufbewahrungsfristen und Verantwortlichkeiten müssen vor einem öffentlichen Betrieb eingerichtet werden.', status: 'draft' }
  ],
  symptoms: [
    { id: 'kiefer', title: 'Kiefer', subtitle: 'Wenn sich Anspannung festsetzt.', intro: 'Kieferknacken, Zähneknirschen oder Beschwerden beim Öffnen des Mundes? Wir betrachten das Zusammenspiel von Kiefer, Kopf und Nacken.', body: 'Am Anfang stehen ein Gespräch und eine individuelle Untersuchung. Gemeinsam besprechen wir, welche therapeutischen Schritte zu Ihrer Situation passen.\n\nUnsere Schwerpunkte umfassen craniomandibuläre und craniofaziale Beschwerden. Je nach Befund verbinden wir physiotherapeutische und logopädische Perspektiven.', service: 'physiotherapie', icon: 'jaw' },
    { id: 'kopfschmerzen', title: 'Kopf & Migräne', subtitle: 'Raum für einen klareren Kopf.', intro: 'Wiederkehrende Kopf- und Nackenbeschwerden können den Alltag stark beeinflussen. Wir nehmen uns Zeit für Ihre Geschichte.', body: 'Wir untersuchen mögliche Zusammenhänge im Bereich von Nacken, Kiefer und Bewegung. Auf Basis Ihres Befundes und Ihrer ärztlichen Abklärung planen wir gemeinsam die Therapie.\n\nNicht jeder Kopfschmerz hat dieselbe Ursache. Die Behandlung wird deshalb an Ihre individuelle Situation angepasst.', service: 'physiotherapie', icon: 'head' },
    { id: 'tinnitus', title: 'Tinnitus', subtitle: 'Zusammenhänge verstehen.', intro: 'Bei Ohrgeräuschen kann es sinnvoll sein, auch Kiefer und Halswirbelsäule in die Untersuchung einzubeziehen.', body: 'Nach ärztlicher Abklärung betrachten wir mögliche funktionelle Zusammenhänge. Die Auswahl der therapeutischen Maßnahmen richtet sich nach Ihrem individuellen Befund.\n\nEine Behandlung ist keine Garantie dafür, dass Ohrgeräusche verschwinden. Wir besprechen Möglichkeiten und Ziele offen mit Ihnen.', service: 'physiotherapie', icon: 'ear' },
    { id: 'schwindel', title: 'Schwindel', subtitle: 'Wieder mehr Sicherheit finden.', intro: 'Wir begleiten Sie bei ärztlich abgeklärten Schwindelbeschwerden mit einem individuell abgestimmten Therapieansatz.', body: 'Schwindel kann unterschiedliche Ursachen haben. Deshalb sind die ärztliche Abklärung und eine sorgfältige Untersuchung wichtige Grundlagen.\n\nGemeinsam arbeiten wir an den für Sie relevanten Bewegungen und Alltagssituationen.', service: 'physiotherapie', icon: 'balance' },
    { id: 'unfall-operation', title: 'Unfall & OP', subtitle: 'Schritt für Schritt zurück.', intro: 'Nach einer Verletzung oder Operation unterstützen wir Sie dabei, Bewegung und Vertrauen in Ihren Körper zurückzugewinnen.', body: 'Wir stimmen die Therapie auf den Heilungsverlauf, ärztliche Vorgaben und Ihre persönlichen Ziele ab.\n\nBeweglichkeit, Kraft und die Anforderungen Ihres Alltags bilden dabei den Ausgangspunkt für einen gemeinsamen Plan.', service: 'physiotherapie', icon: 'movement' }
  ],
  services: [
    { id: 'physiotherapie', title: 'Physiotherapie', tag: 'BEWEGUNG MIT PERSPEKTIVE', intro: 'Bewegung wieder möglich machen. Wir begleiten Sie bei akuten und anhaltenden Beschwerden – individuell, aufmerksam und mit einem klaren Plan.', body: 'Im Mittelpunkt stehen Ihre Beweglichkeit, Belastbarkeit und persönlichen Ziele. Aus Gespräch und Untersuchung entsteht ein Behandlungsplan, den wir gemeinsam weiterentwickeln.', methods: 'CRAFTA® & CMD|Ein Schwerpunkt auf dem Zusammenspiel von Kiefer, Gesicht, Kopf und Halswirbelsäule.\nManuelle Therapie|Individuell ausgewählte Untersuchung und Behandlung des Bewegungsapparats.\nFDM & Faszienbehandlung|Faszienbezogene Ansätze werden abhängig vom Befund und in Absprache mit Ihnen eingesetzt.' },
    { id: 'osteopathie', title: 'Osteopathie', tag: 'DEN MENSCHEN ALS GANZES SEHEN', intro: 'Ein aufmerksamer Blick auf Zusammenhänge. Wir betrachten Ihre Beschwerden im Kontext des gesamten Bewegungsapparats.', body: 'Ein ausführliches Gespräch und eine individuelle Untersuchung bilden die Grundlage. Die Behandlung und weitere Schritte werden mit Ihnen abgestimmt.', methods: 'Individuelle Untersuchung|Wir nehmen uns Zeit für Ihre Vorgeschichte und Ihre aktuellen Beschwerden.\nGemeinsame Therapieplanung|Wir erklären den Befund und besprechen realistische nächste Schritte.' },
    { id: 'logopaedie', title: 'Logopädie', tag: 'KOMMUNIKATION & LEBENSQUALITÄT', intro: 'Sprechen, Stimme und Schlucken gehören zu unserem Alltag. Wir unterstützen Sie, wenn diese Fähigkeiten eingeschränkt sind.', body: 'Die Logopädie beschäftigt sich mit Sprache, Sprechen, Stimme und Schlucken. In der Citypraxis verbinden wir diese Perspektive mit dem Wissen weiterer Fachrichtungen.', methods: 'Stimme & Sprechen|Therapieziele orientieren sich an Ihren persönlichen Anforderungen.\nOrofaziale Funktionen|Wir betrachten das Zusammenspiel von Muskeln und Bewegungen im Mund- und Gesichtsbereich.' },
    { id: 'heilmassage', title: 'Heilmassage', tag: 'ZEIT ZUM LOSLASSEN', intro: 'Gezielte Berührung, bewusst Zeit für Ihren Körper. Die Behandlung wird auf Ihre Bedürfnisse und den Befund abgestimmt.', body: 'Wir besprechen vorab, welche Massageform für Sie geeignet ist. Bitte klären Sie die erforderliche Verordnung vor Ihrem ersten Termin.', methods: 'Klassische Heilmassage|Individuell abgestimmte Behandlung von Muskelregionen.\nManuelle Lymphdrainage|Eine sanfte Behandlungsmethode nach entsprechender Abklärung und Verordnung.' },
    { id: 'rueckenfit', title: 'Rückenfit', tag: 'AKTIV IM ALLTAG', intro: 'Bewegung, die bleibt. Lernen Sie Übungen für einen aktiven Rücken und nehmen Sie neue Impulse mit in Ihren Alltag.', body: 'Informationen zu aktuellen Kursen, Terminen und Preisen erhalten Sie direkt bei unserer Praxis. Wir helfen Ihnen gerne bei der Auswahl des passenden Angebots.', methods: 'Bewegung in der Gruppe|Gemeinsam üben und Bewegungsabläufe kennenlernen.\nÜbungen für zu Hause|Alltagstaugliche Impulse für regelmäßige Bewegung.' }
  ],
  faqs: [
    { id: 'verordnung', title: 'Brauche ich eine ärztliche Verordnung?', body: 'Bitte klären Sie die erforderliche ärztliche Verordnung vor Therapiebeginn. Wenn Sie unsicher sind, welche Unterlagen Sie mitbringen sollen, kontaktieren Sie uns.' },
    { id: 'ersttermin', title: 'Was bringe ich zum ersten Termin mit?', body: 'Bringen Sie Ihre Verordnung und vorhandene relevante Befunde mit. Bequeme Kleidung ist hilfreich. Ihre Fragen und persönlichen Ziele besprechen wir gemeinsam.' },
    { id: 'erstattung', title: 'Wie funktioniert die Rückerstattung?', body: 'Sie bezahlen die Behandlung zunächst selbst und können die Unterlagen bei Ihrer Versicherung einreichen. Ob und in welcher Höhe eine Erstattung möglich ist, hängt von der Behandlung und Ihrer Versicherung ab.' },
    { id: 'zahlung', title: 'Wie kann ich bezahlen?', body: 'Bitte bezahlen Sie Ihre Behandlung direkt vor Ort in bar. Sie erhalten eine Rechnung.' },
    { id: 'absage', title: 'Wie kann ich einen Termin absagen?', body: 'Informieren Sie Ihre Therapeutin oder Ihren Therapeuten möglichst frühzeitig oder schreiben Sie an info@citypraxis.wien. Bitte beachten Sie die bei der Terminvereinbarung mitgeteilten Stornobedingungen.' }
  ],
  team: [], reviews: [], prices: [], reimbursements: []
};
